[package]
name = "r-streamer"
version = "0.1.0"
authors = ["Mnwa <mihan@panfilov.biz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
webrtc-unreliable = "0.4"
env_logger = "0.7"
futures = { version = "0.3" }
hyper = { version = "0.13", features = ["stream"] }
tokio = { version = "0.2", features = ["macros", "udp"] }
log = "0.4"
webrtc-sdp = "0.3"
rand = "0.7"
openssl = "0.10"
byteorder = "1.3"
crc32fast = "1.2"
actix = "0.10.0-alpha.1"
actix-rt = "1.1"
tokio-native-tls = "0.1"